/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:96997c97-fdfc-4dd9-8b26-d3bc76b6180e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Fpon6KOm7",
    "aws_user_pools_web_client_id": "7cmmf0j8fapb5grego4sgq1093",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "SampleProject",
            "region": "us-east-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "DB1",
            "endpoint": "https://pze294grsd.execute-api.us-east-2.amazonaws.com/shela",
            "region": "us-east-2"
        },
        {
            "name": "BSapi",
            "endpoint": "https://ntt28pjn8c.execute-api.us-east-2.amazonaws.com/shela",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
